[project]
name = "warscribe-portal"
version = "0.1.0"
description = "Public facing portal for Team Vindicta"
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "specify-cli",
]

[tool.uv.sources]
specify-cli = { git = "https://github.com/github/spec-kit.git" }
